---
apiVersion: v1
kind: Template
metadata:
  name: python-crash-me-template
  annotations:
    description: Build Config for a sample Python application.
labels:
  name: slack-bot-ngrok
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
    name: python-35-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${EXTERNAL_IMAGE_REPO_URL}/rhscl/python-35-rhel7
      from:
        kind: DockerImage
        name: ${EXTERNAL_IMAGE_REPO_URL}/rhscl/python-35-rhel7
      generation: 1
      name: latest
      referencePolicy:
        type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGE_NAME}:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/themoosman/ocp-python-crash-me.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-35-rhel7:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/status.up
            failureThreshold: 1
            initialDelaySeconds: 45
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 25
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${IMAGE_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:latest
          namespace: ocp-demo
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None

parameters:
  - name: GIT_URI
    description: The ngrok Git URI.
    value: "https://github.com/themoosman/ocp-python-crash-me.git"
    required: true
  - name: GIT_REF
    description: The Git branch.
    value: "master"
  - name: EXTERNAL_IMAGE_REPO_URL
    description: Location where the Red Hat images are stored.
    value: "registry.redhat.io"
  - name: IMAGE_NAME
    description: The name of the image.
    value: py-crash-me
    required: true
  - name: IMAGE_VERSION
    description: The version of the images to use.
    value: "latest"
  - name: NAMESPACE
    description: Target namespace for image. Used to reference the ImageStream source for the image.
    value: ocp-demo
    required: true
  - name: APP_NAME
    description: Application name.
    value: py-crash-me
    required: true
